package it.salvatoremichelelombardo.bluetoothinspector;

import android.bluetooth.*; import android.bluetooth.le.*; import android.content.*; import android.os.*; import android.os.ParcelUuid; import android.util.SparseArray; import java.util.*;

public final class AndroidBluetoothScanner {
    public interface Listener { void onDevice(DeviceInfo d); void onError(String message); }
    private final Context context; private final BluetoothAdapter adapter; private final Listener listener; private BluetoothLeScanner leScanner; private boolean receiverRegistered;
    public AndroidBluetoothScanner(Context c,Listener l){ context=c; listener=l; BluetoothManager m=(BluetoothManager)c.getSystemService(Context.BLUETOOTH_SERVICE); adapter=m==null?null:m.getAdapter(); }
    public void start(){ if(adapter==null){listener.onError("Bluetooth non disponibile");return;} try { for(BluetoothDevice d:adapter.getBondedDevices()) emit(d,0,"classic/paired",null); IntentFilter f=new IntentFilter(BluetoothDevice.ACTION_FOUND); if(Build.VERSION.SDK_INT>=33) context.registerReceiver(receiver,f,Context.RECEIVER_NOT_EXPORTED); else context.registerReceiver(receiver,f); receiverRegistered=true; adapter.startDiscovery(); leScanner=adapter.getBluetoothLeScanner(); if(leScanner!=null) leScanner.startScan(scanCallback); } catch(SecurityException e){listener.onError("Permesso Bluetooth negato");} }
    public void stop(){ try { if(adapter!=null)adapter.cancelDiscovery(); if(leScanner!=null)leScanner.stopScan(scanCallback); if(receiverRegistered){context.unregisterReceiver(receiver);receiverRegistered=false;} } catch(Exception ignored){} }
    private final BroadcastReceiver receiver=new BroadcastReceiver(){ @Override public void onReceive(Context c,Intent i){ if(BluetoothDevice.ACTION_FOUND.equals(i.getAction())){ BluetoothDevice d=i.getParcelableExtra(BluetoothDevice.EXTRA_DEVICE); short r=i.getShortExtra(BluetoothDevice.EXTRA_RSSI,(short)0); if(d!=null)emit(d,r,"classic/discovered",null); } } };
    private final ScanCallback scanCallback=new ScanCallback(){ @Override public void onScanResult(int callbackType,ScanResult r){ emit(r.getDevice(),r.getRssi(),"ble",r.getScanRecord()); } @Override public void onScanFailed(int errorCode){listener.onError("BLE scan error "+errorCode);} };
    private void emit(BluetoothDevice d,int rssi,String transport,ScanRecord record){ try { List<String> uuids=new ArrayList<>(); if(record!=null&&record.getServiceUuids()!=null)for(ParcelUuid u:record.getServiceUuids())uuids.add(u.toString()); if(uuids.isEmpty()&&d.getUuids()!=null)for(ParcelUuid u:d.getUuids())uuids.add(u.toString()); int major=d.getBluetoothClass()==null?0:d.getBluetoothClass().getMajorDeviceClass(); listener.onDevice(new DeviceInfo(d.getName(),d.getAddress(),rssi,d.getBondState(),uuids,transport,d.getType(),major,manufacturer(record),serviceData(record))); } catch(SecurityException e){listener.onError("Permesso Bluetooth negato");} }
    private static String manufacturer(ScanRecord r){ if(r==null)return ""; SparseArray<byte[]> a=r.getManufacturerSpecificData(); StringBuilder s=new StringBuilder(); for(int i=0;i<a.size();i++){ if(i>0)s.append(';'); s.append(a.keyAt(i)).append(':').append(GattInspector.hex(a.valueAt(i))); } return s.toString(); }
    private static String serviceData(ScanRecord r){ if(r==null||r.getServiceData()==null)return ""; StringBuilder s=new StringBuilder(); for(Map.Entry<ParcelUuid,byte[]>e:r.getServiceData().entrySet()){ if(s.length()>0)s.append(';'); s.append(e.getKey()).append(':').append(GattInspector.hex(e.getValue())); } return s.toString(); }
}
