package it.salvatoremichelelombardo.bluetoothinspector;

import android.app.*; import android.os.*; import android.content.*; import android.content.pm.PackageManager; import android.bluetooth.*; import android.graphics.Typeface; import android.view.*; import android.widget.*; import java.util.*;

public final class MainActivity extends Activity {
    private final DeviceAccumulator accumulator=new DeviceAccumulator(); private final List<GattServiceInfo> gatt=new ArrayList<>();
    private ArrayAdapter<String> adapterView; private AndroidBluetoothScanner scanner; private DeviceInfo selected; private TextView status;
    @Override public void onCreate(Bundle b){ super.onCreate(b); buildUi(); ensurePermissions(); }
    private void buildUi(){ LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(24,24,24,24); TextView title=new TextView(this);title.setText("SML Bluetooth Inspector");title.setTextSize(22);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);root.addView(title); status=new TextView(this);status.setText("Pronto. Usa solo dispositivi tuoi o autorizzati.");root.addView(status); LinearLayout bar=new LinearLayout(this); Button scan=new Button(this);scan.setText("Scansiona");Button stop=new Button(this);stop.setText("Stop");Button share=new Button(this);share.setText("Condividi JSON");bar.addView(scan);bar.addView(stop);bar.addView(share);root.addView(bar); ListView list=new ListView(this);adapterView=new ArrayAdapter<>(this,android.R.layout.simple_list_item_1,new ArrayList<>());list.setAdapter(adapterView);root.addView(list,new LinearLayout.LayoutParams(-1,0,1));setContentView(root); scan.setOnClickListener(v->startScan());stop.setOnClickListener(v->{if(scanner!=null)scanner.stop();status.setText("Scansione fermata");});share.setOnClickListener(v->share());list.setOnItemClickListener((p,v,pos,id)->inspect(pos)); }
    private void ensurePermissions(){ List<String> req=BluetoothPermissionManager.requiredRuntimePermissions(Build.VERSION.SDK_INT); List<String> missing=new ArrayList<>();for(String p:req)if(checkSelfPermission(p)!=PackageManager.PERMISSION_GRANTED)missing.add(p);if(!missing.isEmpty())requestPermissions(missing.toArray(new String[0]),7); }
    private void startScan(){ if(scanner!=null)scanner.stop();accumulator.clear();adapterView.clear();scanner=new AndroidBluetoothScanner(this,new AndroidBluetoothScanner.Listener(){public void onDevice(DeviceInfo d){runOnUiThread(()->{accumulator.upsert(d);refresh();});}public void onError(String m){runOnUiThread(()->status.setText(m));}});scanner.start();status.setText("Scansione Classic + BLE in corso…"); }
    private void refresh(){adapterView.clear();for(DeviceInfo d:accumulator.snapshot())adapterView.add(d.display());adapterView.notifyDataSetChanged();}
    private void inspect(int pos){List<DeviceInfo> ds=accumulator.snapshot();if(pos>=ds.size())return;selected=ds.get(pos);status.setText("Selezionato: "+selected.getName()+" — ispezione GATT read-only…"); BluetoothManager m=(BluetoothManager)getSystemService(BLUETOOTH_SERVICE); if(m==null||m.getAdapter()==null)return; try{BluetoothDevice dev=m.getAdapter().getRemoteDevice(selected.getAddress());new GattInspector(this).inspect(dev,new GattInspector.Listener(){public void onComplete(List<GattServiceInfo>s){runOnUiThread(()->{gatt.clear();gatt.addAll(s);status.setText("GATT: "+s.size()+" servizi. Pronto per export JSON.");});}public void onError(String e){runOnUiThread(()->status.setText("GATT: "+e));}});}catch(Exception e){status.setText("Dettagli base disponibili; GATT non disponibile: "+e.getMessage());}}
    private void share(){if(selected==null){status.setText("Seleziona prima un dispositivo");return;}String json=DeviceReportJson.serialize(selected,gatt);Intent i=new Intent(Intent.ACTION_SEND);i.setType("application/json");i.putExtra(Intent.EXTRA_TEXT,json);startActivity(Intent.createChooser(i,"Condividi report Bluetooth"));}
    @Override protected void onDestroy(){if(scanner!=null)scanner.stop();super.onDestroy();}
}
